---
instances: 
 - name: ubuntu2004
   image: images:ubuntu/focal/cloud
   type: container
   profile: profile3
   count: 1
 - name: vm-centos
   image: images:centos/9-Stream/cloud
   type: virtual-machine
   profile: profile4
   count: 0

networks:
 - name: network2

profiles:
 - name: profile3
   network: network2
 - name: profile4
   network: network2
